# Generated by Django 5.2.3 on 2025-08-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techstack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstack',
            name='percent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
