# Generated by Django 5.2.3 on 2025-08-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techstack', '0002_techstack_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='techstack/images/'),
        ),
    ]
