# Generated by Django 5.2.3 on 2025-08-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techstack', '0003_alter_techstack_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstack',
            name='time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
