# Generated by Django 5.2.3 on 2025-08-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techstack', '0004_techstack_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstack',
            name='public',
            field=models.BooleanField(default=True, verbose_name='公開'),
            preserve_default=False,
        ),
    ]
