# Generated by Django 5.2.3 on 2025-08-02 01:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='タグ名')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag', to='history.category')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='タイトル')),
                ('content', models.TextField(max_length=500, verbose_name='内容')),
                ('history_day', models.DateTimeField(verbose_name='日付')),
                ('start_day', models.DateTimeField(blank=True, null=True, verbose_name='開始日時')),
                ('end_day', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('public', models.BooleanField(verbose_name='公開')),
                ('oneday', models.BooleanField(verbose_name='終日')),
                ('url', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='history.category')),
                ('tag', models.ManyToManyField(related_name='tag', to='history.tag')),
            ],
        ),
    ]
