# Generated by Django 5.2.3 on 2025-08-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='history_day',
        ),
        migrations.AlterField(
            model_name='history',
            name='start_day',
            field=models.DateTimeField(verbose_name='開始日時'),
        ),
    ]
