# Generated by Django 5.2.3 on 2025-08-02 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_remove_history_history_day_alter_history_start_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='oneday',
        ),
    ]
