# Generated by Django 5.2.3 on 2025-08-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='content',
            field=models.TextField(max_length=500, verbose_name='内容'),
        ),
    ]
