# Generated by Django 5.2.3 on 2025-08-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_work_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
