# Generated by Django 5.2.3 on 2025-06-23 11:31

import django.db.models.deletion
import markdownx.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('summary', models.CharField(blank=True, max_length=100, null=True, verbose_name='要約')),
                ('created_day', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_day', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('content', markdownx.models.MarkdownxField(verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='タグ名')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentater', models.CharField(max_length=100, verbose_name='コメント者')),
                ('content', models.TextField(verbose_name='コメント')),
                ('day', models.DateTimeField(auto_now_add=True, verbose_name='コメント日時')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='blog.tag'),
        ),
    ]
