# Generated by Django 5.2.3 on 2025-06-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_category_alter_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='plain_content',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
