# Generated by Django 5.2.3 on 2025-06-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='recomment',
        ),
    ]
