# Generated by Django 5.2.3 on 2025-06-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_tag_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='article',
        ),
    ]
