# Generated by Django 5.2.3 on 2025-07-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='public',
            field=models.BooleanField(default=True, verbose_name='公開'),
            preserve_default=False,
        ),
    ]
