# Generated by Django 5.2.3 on 2025-06-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_tag_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='要約'),
        ),
    ]
