# Generated by Django 5.2.3 on 2025-08-02 04:55

import django.db.models.deletion
import markdownx.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='タグ名')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag', to='miniblog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Miniblog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('summary', models.CharField(blank=True, max_length=100, null=True, verbose_name='要約')),
                ('created_day', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_day', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('content', markdownx.models.MarkdownxField(verbose_name='内容')),
                ('plain_content', models.TextField(blank=True, editable=False)),
                ('public', models.BooleanField(verbose_name='公開')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Miniblog', to='miniblog.category')),
                ('tag', models.ManyToManyField(related_name='tag', to='miniblog.tag')),
            ],
        ),
    ]
