# Generated by Django 5.2.3 on 2025-07-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/images/'),
        ),
    ]
