# Generated by Django 5.2.3 on 2025-08-01 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='タグ名')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='タイトル')),
                ('content', models.TextField(max_length=500, verbose_name='内容')),
                ('techcotent', models.TextField(max_length=500, verbose_name='技術内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/images/')),
                ('created_day', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_day', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('public', models.BooleanField(verbose_name='公開')),
                ('url', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='product.category')),
                ('tag', models.ManyToManyField(related_name='tag', to='product.tag')),
            ],
        ),
    ]
