# Generated by Django 5.2.3 on 2025-08-02 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='techcotent',
            new_name='techcontent',
        ),
    ]
